/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PdfToggleDarkModePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var PDF_DARK_CLASS = "pdf-dark-mode";
var SELECTORS = [
  ".pdfViewer",
  ".pdf-sidebar-container img.thumbnailImage",
  ".pdf-cropped-embed"
];
var LIGHTBOX_IMG_SELECTOR = ".lightbox .media-wrapper img, .lightbox .lightbox-media img";
var EXPECT_PDF_LIGHTBOX_CLASS = "pdf-tdm-expect-pdf-lightbox";
var EXPECT_PDF_LIGHTBOX_TIMEOUT_MS = 1e3;
var BAKED_ATTR = "data-pdf-tdm-baked";
var ORIGINAL_SRC_ATTR = "data-pdf-tdm-original-src";
var CSS_VAR_INVERT = "--pdf-tdm-invert";
var CSS_VAR_HUE = "--pdf-tdm-hue";
var CSS_VAR_BRIGHTNESS = "--pdf-tdm-brightness";
var CSS_VAR_FIND_HIGHLIGHT = "--pdf-tdm-find-highlight";
var HEX_COLOR_RE = /^#?([0-9a-fA-F]{6})$/;
var HEX_COLOR_SHORT_RE = /^#?([0-9a-fA-F]{3})$/;
var BRIGHTNESS_MIN = 0.2;
var BRIGHTNESS_MAX = 2;
var BRIGHTNESS_UI_MIN = 20;
var BRIGHTNESS_UI_MAX = 200;
var SLIDER_STEP = 5;
var TOOLBAR_ROOT_CLS = "pdf-tdm-toolbar";
var TOOLBAR_SPACER_CLS = "pdf-toolbar-spacer pdf-tdm-spacer";
var PDF_TOOLBAR_SELECTOR = ".pdf-toolbar:not(.pdf-findbar)";
var HIDE_LINK_ANNOTATIONS_CLASS = "pdf-tdm-hide-link-annotations";
var LINK_OUTLINE_MARK = "data-pdf-tdm-outline-managed";
var LINK_ANNOTATION_SELECTORS = [
  ".pdfViewer .annotationLayer section",
  ".pdfViewer .annotationLayer section.linkAnnotation",
  ".pdfViewer .annotationLayer .linkAnnotation > a",
  ".pdfViewer .annotationLayer a"
];
var HIDE_OUTLINE_PROPS = {
  "border-width": "0",
  "border-style": "none",
  "border-color": "transparent",
  "outline-width": "0",
  "outline-style": "none",
  "outline-color": "transparent",
  "box-shadow": "none"
};
var HIDE_OUTLINE_PROP_KEYS = Object.keys(HIDE_OUTLINE_PROPS);
var PDFJS_SEARCH_SETTINGS_KEY = "pdfjs-search-settings";
var DEFAULT_SETTINGS = {
  isDark: false,
  adaptToTheme: false,
  conversionAmount: 0.9,
  hueRotation: 180,
  brightness: 1,
  showLinkAnnotations: true,
  findHighlightColor: "#ffc400",
  showToolbarButtons: true
};
var DEFAULT_DARKNESS_PERCENT = 90;
var DEFAULT_COLOR_PERCENT = 50;
var DEFAULT_BRIGHTNESS_PERCENT = 100;
function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}
function snapPercent(value, min, max, step = SLIDER_STEP) {
  if (Number.isNaN(value)) {
    return min;
  }
  const clamped = clamp(value, min, max);
  const snapped = Math.round(clamped / step) * step;
  return clamp(snapped, min, max);
}
function clampBrightness(value) {
  if (Number.isNaN(value)) {
    return DEFAULT_SETTINGS.brightness;
  }
  return clamp(value, BRIGHTNESS_MIN, BRIGHTNESS_MAX);
}
function brightnessToPercent(brightness) {
  return snapPercent(
    Math.round(clampBrightness(brightness) * 100),
    BRIGHTNESS_UI_MIN,
    BRIGHTNESS_UI_MAX
  );
}
function percentToBrightness(percent) {
  return clampBrightness(
    snapPercent(percent, BRIGHTNESS_UI_MIN, BRIGHTNESS_UI_MAX) / 100
  );
}
function darknessToPercent(conversionAmount) {
  return snapPercent(Math.round(conversionAmount * 100), 0, 100);
}
function percentToDarkness(percent) {
  return snapPercent(percent, 0, 100) / 100;
}
function colorToPercent(hueRotation) {
  return snapPercent(Math.round(hueRotation / 360 * 100), 0, 100);
}
function percentToColor(percent) {
  return snapPercent(percent, 0, 100) / 100 * 360;
}
function isPdfSearchSettingsRecord(value) {
  return typeof value === "object" && value !== null;
}
function parseUnknownJson(text) {
  return JSON.parse(text);
}
function normalizeHexColor(value, fallback) {
  if (typeof value !== "string") {
    return fallback;
  }
  const trimmed = value.trim();
  const full = HEX_COLOR_RE.exec(trimmed);
  if (full) {
    return `#${full[1].toLowerCase()}`;
  }
  const short = HEX_COLOR_SHORT_RE.exec(trimmed);
  if (short) {
    const [r, g, b] = short[1];
    return `#${r}${r}${g}${g}${b}${b}`.toLowerCase();
  }
  return fallback;
}
var PdfToggleDarkModePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.settings = { ...DEFAULT_SETTINGS };
    this.statusBarEl = null;
    this.ribbonEl = null;
    this.observer = null;
    this.applyTimer = null;
    this.saveTimer = null;
    this.themeSyncTimer = null;
    /** Clears {@link EXPECT_PDF_LIGHTBOX_CLASS} if lightbox never mounts. */
    this.expectLightboxTimer = null;
    /**
     * Crop img src from the last dark-mode PDF++ crop pointerdown.
     * Used to match the lightbox without rescanning every embed on each mutation.
     */
    this.pendingCropSrc = null;
    /**
     * Canvas-baked inverted data URL for {@link pendingCropSrc}.
     * Lightbox animates these pixels without a live CSS filter (smooth zoom).
     */
    this.pendingBakedSrc = null;
    /**
     * Cache: `${src}|invert|hue|brightness` → baked data URL.
     * Invalidated when appearance settings change.
     */
    this.bakeCache = /* @__PURE__ */ new Map();
    /** Prior inline values for annotation nodes we overrode with setCssProps. */
    this.outlineStyleBackup = /* @__PURE__ */ new WeakMap();
    /** Live toolbar control roots we mounted (for sync + cleanup). */
    this.toolbarRoots = /* @__PURE__ */ new Set();
    /** Find-bars we already restored Highlight all=off on (once per instance). */
    this.restoredFindBars = /* @__PURE__ */ new WeakSet();
  }
  async onload() {
    await this.loadSettings();
    this.restoreObsidianFindHighlightAllOff();
    if (this.settings.adaptToTheme) {
      this.settings.isDark = this.isAppThemeDark();
    }
    this.ribbonEl = this.addRibbonIcon(
      this.iconName(),
      this.ribbonTooltip(),
      () => {
        void this.toggleMode();
      }
    );
    this.ribbonEl.addClass("pdf-toggle-dark-mode-ribbon");
    this.statusBarEl = this.addStatusBarItem();
    this.statusBarEl.addClass("mod-clickable", "pdf-toggle-dark-mode-status");
    this.statusBarEl.setAttr("role", "button");
    this.statusBarEl.setAttr("tabindex", "0");
    this.registerDomEvent(this.statusBarEl, "click", () => {
      void this.toggleMode();
    });
    this.registerDomEvent(this.statusBarEl, "keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        void this.toggleMode();
      }
    });
    this.addCommand({
      id: "toggle-pdf-dark-mode",
      name: "Toggle PDF dark/light mode",
      callback: () => {
        void this.toggleMode();
      }
    });
    this.addSettingTab(new PdfDarkModeSettingTab(this.app, this));
    this.updateUi();
    this.applyAppearanceVars();
    this.applyLinkAnnotationStyle();
    this.applyModeToDom();
    this.injectToolbarControls();
    this.registerEvent(
      this.app.workspace.on("layout-change", () => this.scheduleApply())
    );
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", () => this.scheduleApply())
    );
    this.registerEvent(
      this.app.workspace.on("css-change", () => this.scheduleThemeSync())
    );
    const media = window.matchMedia("(prefers-color-scheme: dark)");
    const onSystemScheme = () => this.scheduleThemeSync();
    media.addEventListener("change", onSystemScheme);
    this.register(() => media.removeEventListener("change", onSystemScheme));
    this.registerDomEvent(
      document,
      "pointerdown",
      (e) => {
        this.onPossiblePdfCropLightboxGesture(e);
      },
      { capture: true }
    );
    this.observer = new MutationObserver((mutations) => {
      if (this.mutationsIncludeLightbox(mutations)) {
        this.applyLightboxDarkModeImmediate();
      } else if (this.mutationsMayAffectPdf(mutations)) {
        this.scheduleApply();
      }
    });
    this.observer.observe(document.body, {
      childList: true,
      subtree: true
    });
    this.register(() => {
      var _a;
      (_a = this.observer) == null ? void 0 : _a.disconnect();
      this.observer = null;
      if (this.applyTimer !== null) {
        window.clearTimeout(this.applyTimer);
        this.applyTimer = null;
      }
      if (this.saveTimer !== null) {
        window.clearTimeout(this.saveTimer);
        this.saveTimer = null;
      }
      if (this.themeSyncTimer !== null) {
        window.clearTimeout(this.themeSyncTimer);
        this.themeSyncTimer = null;
      }
      this.clearExpectPdfLightbox();
      this.clearBakeState();
      this.clearAppearanceVars();
      this.clearLinkAnnotationStyle();
      this.removeAllToolbarControls();
    });
  }
  onunload() {
    var _a;
    (_a = this.observer) == null ? void 0 : _a.disconnect();
    this.observer = null;
    if (this.applyTimer !== null) {
      window.clearTimeout(this.applyTimer);
      this.applyTimer = null;
    }
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
      this.saveTimer = null;
    }
    if (this.themeSyncTimer !== null) {
      window.clearTimeout(this.themeSyncTimer);
      this.themeSyncTimer = null;
    }
    this.clearExpectPdfLightbox();
    this.clearBakeState();
    this.setClassOnTargets(false);
    this.clearAppearanceVars();
    this.clearLinkAnnotationStyle();
    this.removeAllToolbarControls();
  }
  /** Whether Obsidian’s current UI theme is dark (`theme-dark` on body). */
  isAppThemeDark() {
    return document.body.classList.contains("theme-dark");
  }
  /**
   * Debounce theme-driven mode sync so css-change + system media query
   * can settle after Obsidian applies `theme-dark` / `theme-light`.
   */
  scheduleThemeSync() {
    if (!this.settings.adaptToTheme) {
      return;
    }
    if (this.themeSyncTimer !== null) {
      window.clearTimeout(this.themeSyncTimer);
    }
    this.themeSyncTimer = window.setTimeout(() => {
      this.themeSyncTimer = null;
      void this.syncModeFromTheme();
    }, 50);
  }
  /**
   * When Adapt to theme is on, set PDF dark/light from Obsidian’s theme.
   * No-op when the setting is off.
   */
  async syncModeFromTheme() {
    if (!this.settings.adaptToTheme) {
      return;
    }
    const isDark = this.isAppThemeDark();
    if (this.settings.isDark === isDark) {
      this.applyModeToDom();
      this.syncAllToolbarControls();
      return;
    }
    this.settings.isDark = isDark;
    await this.saveSettings();
    this.updateUi();
    this.applyModeToDom();
    this.syncAllToolbarControls();
  }
  /**
   * Only rescan when added/removed nodes might include PDF viewer pieces.
   * Avoids applying on every trivial DOM change in the vault UI.
   */
  mutationsMayAffectPdf(mutations) {
    for (const mutation of mutations) {
      if (this.nodesMayIncludePdf(mutation.addedNodes)) {
        return true;
      }
      if (this.nodesMayIncludePdf(mutation.removedNodes)) {
        return true;
      }
    }
    return false;
  }
  nodesMayIncludePdf(nodes) {
    var _a, _b;
    for (let i = 0; i < nodes.length; i++) {
      const node = nodes[i];
      if (!node.instanceOf(HTMLElement)) {
        continue;
      }
      if (((_a = node.matches) == null ? void 0 : _a.call(
        node,
        ".pdfViewer, .pdf-sidebar-container, .thumbnailImage, .pdf-container, .workspace-leaf, .annotationLayer, .linkAnnotation, .pdf-toolbar, .pdf-cropped-embed, .internal-embed"
      )) || ((_b = node.querySelector) == null ? void 0 : _b.call(
        node,
        ".pdfViewer, .pdf-sidebar-container img.thumbnailImage, .thumbnailImage, .annotationLayer, .linkAnnotation, .pdf-toolbar, .pdf-cropped-embed"
      ))) {
        return true;
      }
    }
    return false;
  }
  /** True when a mutation batch adds/removes lightbox UI. */
  mutationsIncludeLightbox(mutations) {
    for (const mutation of mutations) {
      if (this.nodesMatchLightbox(mutation.addedNodes) || this.nodesMatchLightbox(mutation.removedNodes)) {
        return true;
      }
    }
    return false;
  }
  nodesMatchLightbox(nodes) {
    var _a, _b, _c;
    for (let i = 0; i < nodes.length; i++) {
      const node = nodes[i];
      if (!node.instanceOf(HTMLElement)) {
        continue;
      }
      if (((_a = node.matches) == null ? void 0 : _a.call(node, ".lightbox, .lightbox-media, .media-wrapper")) || ((_b = node.querySelector) == null ? void 0 : _b.call(
        node,
        ".lightbox, .lightbox-media, .media-wrapper"
      )) || // Img may be inserted alone under an existing lightbox shell
      node.instanceOf(HTMLImageElement) && Boolean((_c = node.closest) == null ? void 0 : _c.call(node, ".lightbox"))) {
        return true;
      }
    }
    return false;
  }
  /**
   * pointerdown on a PDF++ crop while dark mode is on → expect a lightbox.
   * Pre-bake inverted pixels from the already-loaded crop img so the popup
   * can animate without a live CSS filter (filter+transform is janky).
   */
  onPossiblePdfCropLightboxGesture(e) {
    if (!this.settings.isDark) {
      return;
    }
    const target = e.target;
    if (!target || !target.instanceOf(HTMLElement)) {
      return;
    }
    const crop = target.closest(".pdf-cropped-embed");
    if (!crop) {
      return;
    }
    const cropImg = crop.querySelector("img");
    if (!cropImg || !cropImg.instanceOf(HTMLImageElement)) {
      return;
    }
    const src = cropImg.getAttribute("src");
    if (!src) {
      return;
    }
    this.pendingCropSrc = src;
    this.pendingBakedSrc = this.getBakedInvertedSrc(cropImg, src);
    this.beginExpectPdfLightbox();
  }
  beginExpectPdfLightbox() {
    document.body.classList.add(EXPECT_PDF_LIGHTBOX_CLASS);
    if (this.expectLightboxTimer !== null) {
      window.clearTimeout(this.expectLightboxTimer);
    }
    this.expectLightboxTimer = window.setTimeout(() => {
      this.expectLightboxTimer = null;
      this.clearExpectPdfLightbox();
      this.pendingCropSrc = null;
      this.pendingBakedSrc = null;
    }, EXPECT_PDF_LIGHTBOX_TIMEOUT_MS);
  }
  clearExpectPdfLightbox() {
    document.body.classList.remove(EXPECT_PDF_LIGHTBOX_CLASS);
    if (this.expectLightboxTimer !== null) {
      window.clearTimeout(this.expectLightboxTimer);
      this.expectLightboxTimer = null;
    }
  }
  clearBakeState() {
    this.pendingCropSrc = null;
    this.pendingBakedSrc = null;
    this.bakeCache.clear();
  }
  /** Drop cached bakes when invert/hue/brightness change. */
  invalidateBakeCache() {
    this.bakeCache.clear();
    this.pendingBakedSrc = null;
  }
  /**
   * Sync lightbox invert immediately (no scheduleApply debounce).
   * Prefers canvas-baked src (smooth); CSS filter is fallback only.
   */
  applyLightboxDarkModeImmediate() {
    this.setClassOnLightboxPdfImgs(this.settings.isDark);
    const lightboxOpen = Boolean(document.querySelector(".lightbox"));
    if (!lightboxOpen) {
      this.clearExpectPdfLightbox();
      this.pendingCropSrc = null;
      this.pendingBakedSrc = null;
      return;
    }
    const lbImg = document.querySelector(LIGHTBOX_IMG_SELECTOR);
    if (!this.settings.isDark) {
      this.clearExpectPdfLightbox();
      return;
    }
    if (lbImg && lbImg.instanceOf(HTMLElement) && (lbImg.hasAttribute(BAKED_ATTR) || lbImg.classList.contains(PDF_DARK_CLASS))) {
      this.clearExpectPdfLightbox();
    }
  }
  /** Debounce DOM scans triggered by layout/mutation noise. */
  scheduleApply() {
    if (this.applyTimer !== null) {
      window.clearTimeout(this.applyTimer);
    }
    this.applyTimer = window.setTimeout(() => {
      this.applyTimer = null;
      this.applyModeToDom();
      this.injectToolbarControls();
    }, 50);
  }
  async toggleMode() {
    this.settings.isDark = !this.settings.isDark;
    await this.saveSettings();
    this.updateUi();
    this.applyModeToDom();
    this.syncAllToolbarControls();
  }
  /** Push darkness / color / brightness / Find highlight settings into CSS variables. */
  applyAppearanceVars() {
    const invert = clamp(this.settings.conversionAmount, 0, 1);
    const hue = clamp(this.settings.hueRotation, 0, 360);
    const brightness = clampBrightness(this.settings.brightness);
    document.body.setCssProps({
      [CSS_VAR_INVERT]: String(invert),
      [CSS_VAR_HUE]: `${hue}deg`,
      [CSS_VAR_BRIGHTNESS]: String(brightness),
      [CSS_VAR_FIND_HIGHLIGHT]: this.settings.findHighlightColor
    });
  }
  clearAppearanceVars() {
    document.body.setCssProps({
      [CSS_VAR_INVERT]: "",
      [CSS_VAR_HUE]: "",
      [CSS_VAR_BRIGHTNESS]: "",
      [CSS_VAR_FIND_HIGHLIGHT]: ""
    });
  }
  /**
   * Show/hide PDF link annotation outlines.
   *
   * 1) Body class + styles.css (themes / cascade).
   * 2) setCssProps on annotation nodes so PDF.js inline borders (common on
   *    Linux) are overridden — with a backup so re-enabling restores them.
   *
   * Avoids: injected <style>, element.style.setProperty, styles.css priority hacks.
   */
  applyLinkAnnotationStyle() {
    const hide = !this.settings.showLinkAnnotations;
    document.body.classList.toggle(HIDE_LINK_ANNOTATIONS_CLASS, hide);
    if (hide) {
      this.hideLinkAnnotationOutlines();
    } else {
      this.restoreLinkAnnotationOutlines();
    }
  }
  clearLinkAnnotationStyle() {
    document.body.classList.remove(HIDE_LINK_ANNOTATIONS_CLASS);
    this.restoreLinkAnnotationOutlines();
  }
  hideLinkAnnotationOutlines() {
    for (const selector of LINK_ANNOTATION_SELECTORS) {
      document.querySelectorAll(selector).forEach((node) => {
        if (!node.instanceOf(HTMLElement)) {
          return;
        }
        if (!node.hasAttribute(LINK_OUTLINE_MARK)) {
          const backup = {};
          for (const prop of HIDE_OUTLINE_PROP_KEYS) {
            backup[prop] = node.style.getPropertyValue(prop);
          }
          this.outlineStyleBackup.set(node, backup);
          node.setAttribute(LINK_OUTLINE_MARK, "1");
        }
        node.setCssProps(HIDE_OUTLINE_PROPS);
      });
    }
  }
  restoreLinkAnnotationOutlines() {
    document.querySelectorAll(`[${LINK_OUTLINE_MARK}]`).forEach((node) => {
      if (!node.instanceOf(HTMLElement)) {
        return;
      }
      const backup = this.outlineStyleBackup.get(node);
      if (backup) {
        node.setCssProps(backup);
        this.outlineStyleBackup.delete(node);
      } else {
        const clear = {};
        for (const prop of HIDE_OUTLINE_PROP_KEYS) {
          clear[prop] = "";
        }
        node.setCssProps(clear);
      }
      node.removeAttribute(LINK_OUTLINE_MARK);
    });
  }
  applyModeToDom() {
    this.applyAppearanceVars();
    this.applyLinkAnnotationStyle();
    this.setClassOnTargets(this.settings.isDark);
  }
  setClassOnTargets(isDark) {
    for (const selector of SELECTORS) {
      document.querySelectorAll(selector).forEach((el) => {
        el.classList.toggle(PDF_DARK_CLASS, isDark);
      });
    }
    this.setClassOnLightboxPdfImgs(isDark);
  }
  /**
   * Invert lightbox images that came from a PDF++ crop only.
   *
   * Preferred path: replace src with a canvas-baked inverted data URL
   * (no CSS filter → zoom animation stays cheap). Fallback: .pdf-dark-mode
   * CSS filter when bake is unavailable.
   *
   * Matching: pending crop src from pointerdown, else original-src attr,
   * else scan open crop embeds (rare: toggle dark while lightbox already open).
   */
  setClassOnLightboxPdfImgs(isDark) {
    const lightboxImgs = document.querySelectorAll(LIGHTBOX_IMG_SELECTOR);
    if (lightboxImgs.length === 0) {
      return;
    }
    let cropSrcs = null;
    const srcIsPdfCrop = (originalSrc) => {
      if (!originalSrc) {
        return false;
      }
      if (this.pendingCropSrc && originalSrc === this.pendingCropSrc) {
        return true;
      }
      if (!cropSrcs) {
        cropSrcs = this.collectPdfCropEmbedSrcs();
      }
      return cropSrcs.has(originalSrc);
    };
    lightboxImgs.forEach((node) => {
      var _a;
      if (!node.instanceOf(HTMLImageElement)) {
        return;
      }
      const currentSrc = node.getAttribute("src");
      const originalSrc = node.getAttribute(ORIGINAL_SRC_ATTR) || currentSrc;
      const fromPdfCrop = srcIsPdfCrop(originalSrc);
      if (!isDark || !fromPdfCrop) {
        this.restoreLightboxImgIfBaked(node);
        node.classList.remove(PDF_DARK_CLASS);
        return;
      }
      if (node.hasAttribute(BAKED_ATTR) && originalSrc) {
        const expected = this.bakeCache.get(
          this.bakeCacheKey(originalSrc)
        );
        if (expected && node.getAttribute("src") === expected) {
          node.classList.remove(PDF_DARK_CLASS);
          return;
        }
        this.restoreLightboxImgIfBaked(node);
      }
      let baked = null;
      if (this.pendingBakedSrc && originalSrc && originalSrc === this.pendingCropSrc) {
        baked = this.pendingBakedSrc;
      } else if (originalSrc) {
        baked = (_a = this.bakeCache.get(this.bakeCacheKey(originalSrc))) != null ? _a : null;
      }
      if (!baked) {
        baked = this.getBakedInvertedSrc(
          node,
          originalSrc || currentSrc || ""
        );
      }
      if (baked && originalSrc) {
        node.setAttribute(ORIGINAL_SRC_ATTR, originalSrc);
        node.setAttribute(BAKED_ATTR, "1");
        if (node.getAttribute("src") !== baked) {
          node.setAttribute("src", baked);
        }
        node.classList.remove(PDF_DARK_CLASS);
        return;
      }
      node.classList.add(PDF_DARK_CLASS);
    });
  }
  restoreLightboxImgIfBaked(img) {
    const original = img.getAttribute(ORIGINAL_SRC_ATTR);
    if (!original) {
      img.removeAttribute(BAKED_ATTR);
      return;
    }
    if (img.getAttribute("src") !== original) {
      img.setAttribute("src", original);
    }
    img.removeAttribute(ORIGINAL_SRC_ATTR);
    img.removeAttribute(BAKED_ATTR);
  }
  /**
   * Return a data URL with invert/hue/brightness baked in.
   * Uses the in-memory crop/lightbox bitmap (already decoded) — one-shot cost
   * on click, then the lightbox animates plain pixels.
   */
  getBakedInvertedSrc(source, src) {
    if (!src) {
      return null;
    }
    const key = this.bakeCacheKey(src);
    const cached = this.bakeCache.get(key);
    if (cached) {
      return cached;
    }
    const baked = this.bakeInvertedDataUrl(source);
    if (baked) {
      this.bakeCache.set(key, baked);
    }
    return baked;
  }
  bakeCacheKey(src) {
    const invert = clamp(this.settings.conversionAmount, 0, 1);
    const hue = clamp(this.settings.hueRotation, 0, 360);
    const brightness = clampBrightness(this.settings.brightness);
    return `${invert}|${hue}|${brightness}|${src}`;
  }
  bakeInvertedDataUrl(source) {
    try {
      const w = source.naturalWidth || source.width;
      const h = source.naturalHeight || source.height;
      if (!w || !h) {
        return null;
      }
      const canvas = createEl("canvas");
      canvas.width = w;
      canvas.height = h;
      const ctx = canvas.getContext("2d");
      if (!ctx) {
        return null;
      }
      const invert = clamp(this.settings.conversionAmount, 0, 1);
      const hue = clamp(this.settings.hueRotation, 0, 360);
      const brightness = clampBrightness(this.settings.brightness);
      ctx.filter = `invert(${invert}) hue-rotate(${hue}deg) brightness(${brightness})`;
      ctx.drawImage(source, 0, 0, w, h);
      return canvas.toDataURL("image/png");
    } catch (e) {
      return null;
    }
  }
  /** Unique img src values currently rendered inside PDF++ crop embeds. */
  collectPdfCropEmbedSrcs() {
    const srcs = /* @__PURE__ */ new Set();
    document.querySelectorAll(".pdf-cropped-embed img").forEach((node) => {
      if (!node.instanceOf(HTMLImageElement)) {
        return;
      }
      const src = node.getAttribute("src");
      if (src) {
        srcs.add(src);
      }
    });
    return srcs;
  }
  /**
   * Inject dark/light toggle + appearance sliders into each native PDF
   * toolbar (PDF++-style: spacer + control group on the left section).
   */
  injectToolbarControls() {
    if (!this.settings.showToolbarButtons) {
      this.removeAllToolbarControls();
      return;
    }
    for (const root of Array.from(this.toolbarRoots)) {
      if (!root.isConnected) {
        this.toolbarRoots.delete(root);
      }
    }
    document.querySelectorAll(PDF_TOOLBAR_SELECTOR).forEach((toolbar) => {
      if (!toolbar.instanceOf(HTMLElement)) {
        return;
      }
      if (toolbar.querySelector(`.${TOOLBAR_ROOT_CLS}`)) {
        return;
      }
      const first = toolbar.firstElementChild;
      const left = first && first.instanceOf(HTMLElement) ? first : toolbar;
      this.mountToolbarControls(left);
    });
    this.syncAllToolbarControls();
    this.restoreObsidianFindHighlightAllOff();
  }
  /**
   * A previous version turned Obsidian’s PDF “Highlight all” on and saved it.
   * That paints every match as an opaque overlay; on an inverted page those
   * reads as redaction bars. Restore the Obsidian default (off).
   */
  restoreObsidianFindHighlightAllOff() {
    this.clearStoredPdfHighlightAll();
    this.clearLivePdfHighlightAll();
  }
  clearStoredPdfHighlightAll() {
    try {
      const raw = this.app.loadLocalStorage(
        PDFJS_SEARCH_SETTINGS_KEY
      );
      if (raw == null) {
        return;
      }
      const parsed = typeof raw === "string" ? parseUnknownJson(raw) : raw;
      if (!isPdfSearchSettingsRecord(parsed) || parsed.highlightAll !== true) {
        return;
      }
      parsed.highlightAll = false;
      this.app.saveLocalStorage(
        PDFJS_SEARCH_SETTINGS_KEY,
        JSON.stringify(parsed)
      );
    } catch (e) {
    }
  }
  clearLivePdfHighlightAll() {
    var _a;
    const restore = (findBar) => {
      var _a2, _b, _c;
      if (!findBar || this.restoredFindBars.has(findBar)) {
        return;
      }
      this.restoredFindBars.add(findBar);
      if (!((_a2 = findBar.searchSettings) == null ? void 0 : _a2.highlightAll)) {
        return;
      }
      findBar.searchSettings.highlightAll = false;
      (_b = findBar.saveSettings) == null ? void 0 : _b.call(findBar);
      (_c = findBar.dispatchEvent) == null ? void 0 : _c.call(findBar, "highlightallchange");
    };
    for (const leaf of this.app.workspace.getLeavesOfType("pdf")) {
      const viewer = leaf.view.viewer;
      if (!viewer) {
        continue;
      }
      if ((_a = viewer.child) == null ? void 0 : _a.findBar) {
        restore(viewer.child.findBar);
      } else if (typeof viewer.then === "function") {
        viewer.then((child) => restore(child.findBar));
      }
    }
  }
  mountToolbarControls(parent) {
    parent.createDiv({ cls: TOOLBAR_SPACER_CLS });
    const root = parent.createDiv({ cls: TOOLBAR_ROOT_CLS });
    this.toolbarRoots.add(root);
    const toggleBtn = root.createDiv({
      cls: "clickable-icon pdf-tdm-toggle",
      attr: { role: "button", tabindex: "0" }
    });
    (0, import_obsidian.setIcon)(toggleBtn, this.iconName());
    (0, import_obsidian.setTooltip)(toggleBtn, this.ribbonTooltip());
    this.registerDomEvent(toggleBtn, "click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      void this.toggleMode();
    });
    this.registerDomEvent(toggleBtn, "keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        void this.toggleMode();
      }
    });
    const sliders = root.createDiv({ cls: "pdf-tdm-sliders" });
    this.createToolbarSlider(sliders, {
      key: "darkness",
      label: "Dark",
      ariaLabel: "Darkness",
      title: "Darkness \u2014 how strongly light pages turn dark (5% steps)",
      min: 0,
      max: 100,
      defaultPercent: DEFAULT_DARKNESS_PERCENT,
      getValue: () => darknessToPercent(this.settings.conversionAmount),
      setValue: (percent) => {
        this.settings.conversionAmount = percentToDarkness(percent);
      },
      onReset: () => this.resetDarknessToDefault()
    });
    this.createToolbarSlider(sliders, {
      key: "color",
      label: "Color",
      ariaLabel: "Color correction",
      title: "Color correction \u2014 drag until charts/photos look natural (5% steps)",
      min: 0,
      max: 100,
      defaultPercent: DEFAULT_COLOR_PERCENT,
      getValue: () => colorToPercent(this.settings.hueRotation),
      setValue: (percent) => {
        this.settings.hueRotation = percentToColor(percent);
      },
      onReset: () => this.resetColorToDefault()
    });
    this.createToolbarSlider(sliders, {
      key: "brightness",
      label: "Bright",
      ariaLabel: "Brightness",
      title: "Brightness \u2014 20% min, 200% max (5% steps)",
      min: BRIGHTNESS_UI_MIN,
      max: BRIGHTNESS_UI_MAX,
      defaultPercent: DEFAULT_BRIGHTNESS_PERCENT,
      getValue: () => brightnessToPercent(this.settings.brightness),
      setValue: (percent) => {
        this.settings.brightness = percentToBrightness(percent);
      },
      onReset: () => this.resetBrightnessToDefault()
    });
    this.createToolbarFindColorGroup(sliders);
  }
  /**
   * Compact Find highlight swatch (dark mode only).
   * Native `input type=color` so the OS picker opens from the toolbar.
   */
  createToolbarFindColorGroup(parent) {
    const group = parent.createDiv({
      cls: "pdf-tdm-slider-group pdf-tdm-find-colors"
    });
    group.createSpan({
      cls: "pdf-tdm-slider-label",
      text: "Find"
    });
    this.createToolbarColorInput(group, {
      key: "find",
      ariaLabel: "Find highlight color",
      title: "Find highlight \u2014 color of the current match",
      getValue: () => this.settings.findHighlightColor,
      setValue: (hex) => {
        this.settings.findHighlightColor = hex;
      },
      defaultValue: DEFAULT_SETTINGS.findHighlightColor
    });
    const resetBtn = group.createDiv({
      cls: "clickable-icon pdf-tdm-slider-reset",
      attr: {
        role: "button",
        tabindex: "0",
        "aria-label": "Reset Find highlight color to default"
      }
    });
    (0, import_obsidian.setIcon)(resetBtn, "rotate-ccw");
    (0, import_obsidian.setTooltip)(
      resetBtn,
      `Reset Find highlight to default (${DEFAULT_SETTINGS.findHighlightColor})`
    );
    const doReset = (e) => {
      e.preventDefault();
      e.stopPropagation();
      void this.resetFindHighlightToDefault();
    };
    this.registerDomEvent(resetBtn, "click", doReset);
    this.registerDomEvent(resetBtn, "keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        doReset(e);
      }
    });
  }
  createToolbarColorInput(parent, opts) {
    const input = parent.createEl("input", {
      cls: `pdf-tdm-color-input pdf-tdm-color-input-${opts.key}`,
      attr: {
        type: "color",
        "aria-label": opts.ariaLabel
      }
    });
    input.value = opts.getValue();
    (0, import_obsidian.setTooltip)(input, opts.title);
    const applyColor = () => {
      const hex = normalizeHexColor(input.value, opts.defaultValue);
      input.value = hex;
      opts.setValue(hex);
      this.applyAppearanceVars();
      this.syncAllToolbarControls(input);
    };
    this.registerDomEvent(input, "input", () => {
      applyColor();
      this.scheduleSaveSettings();
    });
    this.registerDomEvent(input, "change", () => {
      applyColor();
      this.scheduleSaveSettings();
    });
  }
  createToolbarSlider(parent, opts) {
    const group = parent.createDiv({
      cls: `pdf-tdm-slider-group pdf-tdm-slider-${opts.key}`
    });
    group.createSpan({
      cls: "pdf-tdm-slider-label",
      text: opts.label
    });
    const input = group.createEl("input", {
      cls: `slider pdf-tdm-slider pdf-tdm-slider-input-${opts.key}`,
      attr: {
        type: "range",
        min: String(opts.min),
        max: String(opts.max),
        step: String(SLIDER_STEP),
        "aria-label": opts.ariaLabel
      }
    });
    input.value = String(opts.getValue());
    (0, import_obsidian.setTooltip)(input, opts.title);
    const valueEl = group.createSpan({
      cls: "pdf-tdm-slider-value",
      text: `${opts.getValue()}%`
    });
    const resetBtn = group.createDiv({
      cls: "clickable-icon pdf-tdm-slider-reset",
      attr: {
        role: "button",
        tabindex: "0",
        "aria-label": `Reset ${opts.ariaLabel} to ${opts.defaultPercent}%`
      }
    });
    (0, import_obsidian.setIcon)(resetBtn, "rotate-ccw");
    (0, import_obsidian.setTooltip)(
      resetBtn,
      `Reset ${opts.ariaLabel} to default (${opts.defaultPercent}%)`
    );
    const applyPercent = (percent) => {
      const snapped = snapPercent(percent, opts.min, opts.max);
      input.value = String(snapped);
      opts.setValue(snapped);
      valueEl.setText(`${snapped}%`);
      this.invalidateBakeCache();
      this.applyAppearanceVars();
      if (this.settings.isDark) {
        this.setClassOnTargets(true);
      }
      this.syncAllToolbarControls(input);
    };
    const onInput = () => {
      applyPercent(Math.round(Number(input.value)));
      this.scheduleSaveSettings();
    };
    const doReset = (e) => {
      e.preventDefault();
      e.stopPropagation();
      void opts.onReset();
    };
    this.registerDomEvent(input, "input", onInput);
    this.registerDomEvent(input, "change", onInput);
    this.registerDomEvent(resetBtn, "click", doReset);
    this.registerDomEvent(resetBtn, "keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        doReset(e);
      }
    });
  }
  /** Debounced persist so slider drags don’t thrash disk. */
  scheduleSaveSettings() {
    if (this.saveTimer !== null) {
      window.clearTimeout(this.saveTimer);
    }
    this.saveTimer = window.setTimeout(() => {
      this.saveTimer = null;
      void this.saveSettings();
    }, 200);
  }
  /**
   * Refresh icons, slider values, and visibility on every mounted toolbar.
   * @param exceptInput while dragging, skip this input and skip icon/tooltip
   *        rewrites (only mirror values to other open PDF toolbars)
   */
  syncAllToolbarControls(exceptInput) {
    const isDark = this.settings.isDark;
    const darknessPct = darknessToPercent(this.settings.conversionAmount);
    const colorPct = colorToPercent(this.settings.hueRotation);
    const brightnessPct = brightnessToPercent(this.settings.brightness);
    const icon = this.iconName();
    const tooltip = this.ribbonTooltip();
    const fullChrome = !exceptInput;
    for (const root of this.toolbarRoots) {
      if (!root.isConnected) {
        continue;
      }
      if (fullChrome) {
        const toggleBtn = root.querySelector(".pdf-tdm-toggle");
        if (toggleBtn) {
          (0, import_obsidian.setIcon)(toggleBtn, icon);
          (0, import_obsidian.setTooltip)(toggleBtn, tooltip);
          toggleBtn.toggleClass("is-active", isDark);
        }
        const sliders = root.querySelector(".pdf-tdm-sliders");
        if (sliders) {
          sliders.toggleClass("is-visible", isDark);
          sliders.setAttr(
            "aria-hidden",
            isDark ? "false" : "true"
          );
        }
      }
      const darknessInput = root.querySelector(
        ".pdf-tdm-slider-input-darkness"
      );
      const darknessVal = root.querySelector(
        ".pdf-tdm-slider-darkness .pdf-tdm-slider-value"
      );
      if (darknessInput && darknessInput !== exceptInput) {
        darknessInput.value = String(darknessPct);
      }
      if (darknessVal) {
        darknessVal.setText(`${darknessPct}%`);
      }
      const colorInput = root.querySelector(
        ".pdf-tdm-slider-input-color"
      );
      const colorVal = root.querySelector(
        ".pdf-tdm-slider-color .pdf-tdm-slider-value"
      );
      if (colorInput && colorInput !== exceptInput) {
        colorInput.value = String(colorPct);
      }
      if (colorVal) {
        colorVal.setText(`${colorPct}%`);
      }
      const brightnessInput = root.querySelector(
        ".pdf-tdm-slider-input-brightness"
      );
      const brightnessVal = root.querySelector(
        ".pdf-tdm-slider-brightness .pdf-tdm-slider-value"
      );
      if (brightnessInput && brightnessInput !== exceptInput) {
        brightnessInput.value = String(brightnessPct);
      }
      if (brightnessVal) {
        brightnessVal.setText(`${brightnessPct}%`);
      }
      const findInput = root.querySelector(
        ".pdf-tdm-color-input-find"
      );
      if (findInput && findInput !== exceptInput) {
        findInput.value = this.settings.findHighlightColor;
      }
    }
  }
  removeAllToolbarControls() {
    for (const root of Array.from(this.toolbarRoots)) {
      const prev = root.previousElementSibling;
      if (prev && prev.instanceOf(HTMLElement) && prev.classList.contains("pdf-tdm-spacer")) {
        prev.remove();
      }
      root.remove();
    }
    this.toolbarRoots.clear();
    document.querySelectorAll(`.${TOOLBAR_ROOT_CLS}, .pdf-tdm-spacer`).forEach((el) => el.remove());
  }
  /** Refresh ribbon, status bar, and toolbar chrome for the current mode. */
  updateUi() {
    const label = this.modeLabel();
    const icon = this.iconName();
    const tooltip = this.ribbonTooltip();
    if (this.ribbonEl) {
      (0, import_obsidian.setIcon)(this.ribbonEl, icon);
      this.ribbonEl.setAttr("aria-label", tooltip);
      this.ribbonEl.setAttr("title", tooltip);
    }
    if (this.statusBarEl) {
      this.statusBarEl.empty();
      const iconSpan = this.statusBarEl.createSpan({
        cls: "pdf-toggle-dark-mode-status-icon"
      });
      (0, import_obsidian.setIcon)(iconSpan, icon);
      this.statusBarEl.createSpan({
        text: ` PDF: ${label}`,
        cls: "pdf-toggle-dark-mode-status-text"
      });
      this.statusBarEl.setAttr("aria-label", tooltip);
      this.statusBarEl.setAttr("title", tooltip);
    }
    this.syncAllToolbarControls();
  }
  modeLabel() {
    return this.settings.isDark ? "Dark" : "Light";
  }
  /** Lucide icon names available in Obsidian */
  iconName() {
    return this.settings.isDark ? "moon" : "sun";
  }
  ribbonTooltip() {
    const adapt = this.settings.adaptToTheme ? " \xB7 adapting to theme" : "";
    return this.settings.isDark ? `PDF appearance: Dark (click for Light)${adapt}` : `PDF appearance: Light (click for Dark)${adapt}`;
  }
  async loadSettings() {
    const raw = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, raw);
    this.settings.conversionAmount = percentToDarkness(
      darknessToPercent(Number(this.settings.conversionAmount))
    );
    if (Number.isNaN(Number(raw == null ? void 0 : raw.conversionAmount))) {
      this.settings.conversionAmount = DEFAULT_SETTINGS.conversionAmount;
    }
    this.settings.hueRotation = percentToColor(
      colorToPercent(Number(this.settings.hueRotation))
    );
    if (Number.isNaN(Number(raw == null ? void 0 : raw.hueRotation))) {
      this.settings.hueRotation = DEFAULT_SETTINGS.hueRotation;
    }
    this.settings.brightness = percentToBrightness(
      brightnessToPercent(Number(this.settings.brightness))
    );
    if (raw && typeof raw.brightness !== "number") {
      this.settings.brightness = DEFAULT_SETTINGS.brightness;
    }
    this.settings.showLinkAnnotations = Boolean(
      this.settings.showLinkAnnotations
    );
    if (raw && typeof raw.showLinkAnnotations !== "boolean") {
      this.settings.showLinkAnnotations = DEFAULT_SETTINGS.showLinkAnnotations;
    }
    this.settings.adaptToTheme = Boolean(this.settings.adaptToTheme);
    if (raw && typeof raw.adaptToTheme !== "boolean") {
      this.settings.adaptToTheme = DEFAULT_SETTINGS.adaptToTheme;
    }
    this.settings.showToolbarButtons = Boolean(
      this.settings.showToolbarButtons
    );
    if (raw && typeof raw.showToolbarButtons !== "boolean") {
      this.settings.showToolbarButtons = DEFAULT_SETTINGS.showToolbarButtons;
    }
    this.settings.findHighlightColor = normalizeHexColor(
      this.settings.findHighlightColor,
      DEFAULT_SETTINGS.findHighlightColor
    );
    delete this.settings.findHighlightSelectedColor;
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  /** Called from the settings tab after a control changes. */
  async onAppearanceSettingChange() {
    await this.saveSettings();
    this.invalidateBakeCache();
    this.applyAppearanceVars();
    this.applyLinkAnnotationStyle();
    if (this.settings.isDark) {
      this.setClassOnTargets(true);
    } else {
      this.setClassOnLightboxPdfImgs(false);
    }
    this.syncAllToolbarControls();
  }
  /** Restore Darkness slider only. */
  async resetDarknessToDefault() {
    this.settings.conversionAmount = DEFAULT_SETTINGS.conversionAmount;
    await this.onAppearanceSettingChange();
  }
  /** Restore Color correction slider only. */
  async resetColorToDefault() {
    this.settings.hueRotation = DEFAULT_SETTINGS.hueRotation;
    await this.onAppearanceSettingChange();
  }
  /** Restore Brightness slider only. */
  async resetBrightnessToDefault() {
    this.settings.brightness = DEFAULT_SETTINGS.brightness;
    await this.onAppearanceSettingChange();
  }
  /** Restore Find highlight color. */
  async resetFindHighlightToDefault() {
    this.settings.findHighlightColor = DEFAULT_SETTINGS.findHighlightColor;
    await this.onAppearanceSettingChange();
  }
};
var PdfDarkModeSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  getSettingDefinitions() {
    return [
      {
        type: "group",
        heading: "PDF appearance",
        items: [
          {
            name: "About",
            desc: "These options only affect how PDFs look when dark mode is on. They do not change the rest of Obsidian."
          },
          {
            name: "Adapt to theme",
            desc: "When on, PDF dark/light mode follows Obsidian\u2019s appearance. If Obsidian uses \u201CAdapt to system\u201D, system-wide light/dark changes are followed too. You can still toggle manually; the next theme change will re-sync.",
            aliases: [
              "follow theme",
              "system theme",
              "match theme",
              "auto dark",
              "adapt to system"
            ],
            control: {
              type: "toggle",
              key: "adaptToTheme",
              defaultValue: false
            }
          },
          {
            name: "Show toolbar buttons",
            desc: "Show the dark/light mode toggle and appearance controls in the PDF viewer toolbar. Turn off to hide them if you prefer using ribbon icons, status bar, or commands.",
            aliases: [
              "toolbar buttons",
              "toolbar controls",
              "pdf toolbar",
              "toolbar toggle",
              "hide toolbar buttons",
              "show toolbar"
            ],
            control: {
              type: "toggle",
              key: "showToolbarButtons",
              defaultValue: true
            }
          },
          {
            name: "Darkness",
            desc: "How strongly light PDF pages turn dark. 90% is the default; 100% is a full dark look; lower values keep pages lighter. Adjusts in 5% steps.",
            aliases: ["conversion amount", "invert", "dark mode strength"],
            control: {
              type: "slider",
              key: "darknessPercent",
              min: 0,
              max: 100,
              step: SLIDER_STEP,
              defaultValue: DEFAULT_DARKNESS_PERCENT,
              displayFormat: (value) => this.darknessLabel(value)
            }
          },
          {
            name: "Reset darkness",
            desc: `Restore Darkness to the default (${DEFAULT_DARKNESS_PERCENT}%).`,
            aliases: ["reset dark", "default darkness"],
            action: () => {
              void this.plugin.resetDarknessToDefault().then(() => {
                this.update();
              });
            }
          },
          {
            name: "Color correction",
            desc: "After darkening, colors (charts, photos, highlights) can look off. Drag until they look natural. 50% works well for most PDFs. Adjusts in 5% steps.",
            aliases: ["hue", "color balance", "color tone"],
            control: {
              type: "slider",
              key: "colorCorrectionPercent",
              min: 0,
              max: 100,
              step: SLIDER_STEP,
              defaultValue: DEFAULT_COLOR_PERCENT,
              displayFormat: (value) => this.colorLabel(value)
            }
          },
          {
            name: "Reset color correction",
            desc: `Restore Color correction to the default (${DEFAULT_COLOR_PERCENT}%).`,
            aliases: ["reset color", "default color", "reset hue"],
            action: () => {
              void this.plugin.resetColorToDefault().then(() => {
                this.update();
              });
            }
          },
          {
            name: "Brightness",
            desc: "Overall brightness after darkening (CSS brightness). Range is 20\u2013200% in 5% steps (below 20% is too dark; above 200% washes out).",
            aliases: [
              "bright",
              "luminance",
              "light level",
              "filter brightness"
            ],
            control: {
              type: "slider",
              key: "brightnessPercent",
              min: BRIGHTNESS_UI_MIN,
              max: BRIGHTNESS_UI_MAX,
              step: SLIDER_STEP,
              defaultValue: DEFAULT_BRIGHTNESS_PERCENT,
              displayFormat: (value) => this.brightnessLabel(value)
            }
          },
          {
            name: "Reset brightness",
            desc: `Restore Brightness to the default (${DEFAULT_BRIGHTNESS_PERCENT}%).`,
            aliases: ["reset bright", "default brightness"],
            action: () => {
              void this.plugin.resetBrightnessToDefault().then(() => {
                this.update();
              });
            }
          },
          {
            name: "Show link outlines",
            desc: "Show the outline boxes around clickable links in PDFs. Turn off to hide those borders while keeping links clickable.",
            aliases: [
              "link annotations",
              "annotation layer",
              "link boxes",
              "link borders"
            ],
            control: {
              type: "toggle",
              key: "showLinkAnnotations",
              defaultValue: true
            }
          },
          {
            name: "Find highlight",
            desc: "Color of the current PDF Find match (Ctrl/Cmd+F) when dark mode is on. The ring is a darker shade of this color. The default light-purple PDF.js mark is almost invisible on darkened pages.",
            aliases: [
              "search highlight",
              "find in file",
              "find color",
              "match color",
              "pdf find",
              "current match"
            ],
            control: {
              type: "color",
              key: "findHighlightColor",
              defaultValue: DEFAULT_SETTINGS.findHighlightColor
            }
          },
          {
            name: "Reset appearance",
            desc: "Restore Darkness, Color correction, Brightness, Show link outlines, and Find highlight to the recommended defaults.",
            action: () => {
              this.plugin.settings.conversionAmount = DEFAULT_SETTINGS.conversionAmount;
              this.plugin.settings.hueRotation = DEFAULT_SETTINGS.hueRotation;
              this.plugin.settings.brightness = DEFAULT_SETTINGS.brightness;
              this.plugin.settings.showLinkAnnotations = DEFAULT_SETTINGS.showLinkAnnotations;
              this.plugin.settings.findHighlightColor = DEFAULT_SETTINGS.findHighlightColor;
              void this.plugin.onAppearanceSettingChange().then(() => {
                this.update();
              });
            }
          }
        ]
      }
    ];
  }
  /**
   * Map friendly slider keys ↔ internal CSS-oriented settings.
   */
  getControlValue(key) {
    if (key === "darknessPercent") {
      return darknessToPercent(this.plugin.settings.conversionAmount);
    }
    if (key === "colorCorrectionPercent") {
      return colorToPercent(this.plugin.settings.hueRotation);
    }
    if (key === "brightnessPercent") {
      return brightnessToPercent(this.plugin.settings.brightness);
    }
    if (key === "findHighlightColor") {
      return this.plugin.settings.findHighlightColor;
    }
    return super.getControlValue(key);
  }
  async setControlValue(key, value) {
    if (key === "darknessPercent") {
      this.plugin.settings.conversionAmount = percentToDarkness(
        Number(value)
      );
      await this.plugin.onAppearanceSettingChange();
      return;
    }
    if (key === "colorCorrectionPercent") {
      this.plugin.settings.hueRotation = percentToColor(Number(value));
      await this.plugin.onAppearanceSettingChange();
      return;
    }
    if (key === "brightnessPercent") {
      this.plugin.settings.brightness = percentToBrightness(Number(value));
      await this.plugin.onAppearanceSettingChange();
      return;
    }
    if (key === "adaptToTheme") {
      this.plugin.settings.adaptToTheme = Boolean(value);
      await this.plugin.saveSettings();
      if (this.plugin.settings.adaptToTheme) {
        await this.plugin.syncModeFromTheme();
      }
      this.plugin.updateUi();
      return;
    }
    if (key === "showToolbarButtons") {
      this.plugin.settings.showToolbarButtons = Boolean(value);
      await this.plugin.saveSettings();
      if (this.plugin.settings.showToolbarButtons) {
        this.plugin.injectToolbarControls();
      } else {
        this.plugin.removeAllToolbarControls();
      }
      return;
    }
    if (key === "findHighlightColor") {
      this.plugin.settings.findHighlightColor = normalizeHexColor(
        value,
        DEFAULT_SETTINGS.findHighlightColor
      );
      await this.plugin.onAppearanceSettingChange();
      return;
    }
    await super.setControlValue(key, value);
    await this.plugin.onAppearanceSettingChange();
  }
  darknessLabel(percent) {
    if (percent === 0)
      return "0% \u2014 off";
    if (percent === DEFAULT_DARKNESS_PERCENT) {
      return `${DEFAULT_DARKNESS_PERCENT}% \u2014 default`;
    }
    if (percent === 100)
      return "100% \u2014 full dark";
    return `${percent}%`;
  }
  colorLabel(percent) {
    if (percent === DEFAULT_COLOR_PERCENT) {
      return `${DEFAULT_COLOR_PERCENT}% \u2014 recommended`;
    }
    if (percent === 0)
      return "0% \u2014 no correction";
    if (percent === 100)
      return "100%";
    return `${percent}%`;
  }
  brightnessLabel(percent) {
    if (percent === DEFAULT_BRIGHTNESS_PERCENT) {
      return `${DEFAULT_BRIGHTNESS_PERCENT}% \u2014 default`;
    }
    if (percent <= BRIGHTNESS_UI_MIN)
      return "20% \u2014 minimum";
    if (percent >= BRIGHTNESS_UI_MAX)
      return "200% \u2014 maximum";
    return `${percent}%`;
  }
};

/* nosourcemap */